### ISSUE TITLE
PHP 7.0 Errors with Zip

### ISSUE THREAD

**Issue by Mte90** [Qafoo/QualityAnalyzer#229]
I got these errors when I executed the package and I don't understand the problems.
```
Analyze source code in /path/of/folder
 * Running source
 * Running coverage
 * Running pdepend
Exception: Command "/opt/QualityAnalyzer/vendor/bin/pdepend '--summary-xml=/tmp/qabbqDQp' '--coderank-mode=inheritance,property,method' '--ignore=lib' '/path/of/folder'" exited with non zero exit code 255: PDepend 2.2.4

Parsing source files:
............................................................    60
............................................................   120
............................................................   180
............................................................   240
............................................................   300
............................................................   360
............................................................   420
............................................................   480
............................................................   540
............................................................   600
............................................................   660
............................................................   720
............................................................   780
............................................................   840
............................................................   900
............................................................   960
............................................................  1020
............................................................  1080
............................................................  1140
............................................................  1200
............................................................  1260
............................................................  1320
............................................................  1380
....................... in /opt/QualityAnalyzer/src/php/Qafoo/Analyzer/Shell.php:54
Stack trace:
#0 /opt/QualityAnalyzer/src/php/Qafoo/Analyzer/Handler/PDepend.php(55): Qafoo\Analyzer\Shell->exec('/opt/QualityAna...', Array)
#1 /opt/QualityAnalyzer/src/php/Qafoo/Analyzer/Command/Analyze.php(136): Qafoo\Analyzer\Handler\PDepend->handle(Object(Qafoo\Analyzer\Project), NULL)
#2 /opt/QualityAnalyzer/vendor/symfony/console/Command/Command.php(259): Qafoo\Analyzer\Command\Analyze->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /opt/QualityAnalyzer/vendor/symfony/console/Application.php(849): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /opt/QualityAnalyzer/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Qafoo\Analyzer\Command\Analyze), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /opt/QualityAnalyzer/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /opt/QualityAnalyzer/bin/analyze(15): Symfony\Component\Console\Application->run()
#7 {main}
 * Running dependencies
Exception: Command "/opt/QualityAnalyzer/vendor/bin/pdepend '--dependency-xml=/tmp/qaBJJCRQ' '--ignore=lib' '/path/of/folder'" exited with non zero exit code 255: PDepend 2.2.4

Parsing source files:
............................................................    60
............................................................   120
............................................................   180
............................................................   240
............................................................   300
............................................................   360
............................................................   420
............................................................   480
............................................................   540
............................................................   600
............................................................   660
............................................................   720
............................................................   780
............................................................   840
............................................................   900
............................................................   960
............................................................  1020
............................................................  1080
............................................................  1140
............................................................  1200
............................................................  1260
............................................................  1320
............................................................  1380
....................... in /opt/QualityAnalyzer/src/php/Qafoo/Analyzer/Shell.php:54
Stack trace:
#0 /opt/QualityAnalyzer/src/php/Qafoo/Analyzer/Handler/Dependencies.php(50): Qafoo\Analyzer\Shell->exec('/opt/QualityAna...', Array)
#1 /opt/QualityAnalyzer/src/php/Qafoo/Analyzer/Command/Analyze.php(136): Qafoo\Analyzer\Handler\Dependencies->handle(Object(Qafoo\Analyzer\Project), NULL)
#2 /opt/QualityAnalyzer/vendor/symfony/console/Command/Command.php(259): Qafoo\Analyzer\Command\Analyze->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /opt/QualityAnalyzer/vendor/symfony/console/Application.php(849): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /opt/QualityAnalyzer/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Qafoo\Analyzer\Command\Analyze), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /opt/QualityAnalyzer/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /opt/QualityAnalyzer/bin/analyze(15): Symfony\Component\Console\Application->run()
#7 {main}
 * Running phpmd
Exception: Command "/opt/QualityAnalyzer/vendor/bin/phpmd '--reportfile' '/tmp/qad8Tj0k' '--exclude' 'lib' '/path/of/folder' 'xml' 'cleancode,codesize,design'" exited with non zero exit code 255:  in /opt/QualityAnalyzer/src/php/Qafoo/Analyzer/Shell.php:54
Stack trace:
#0 /opt/QualityAnalyzer/src/php/Qafoo/Analyzer/Handler/PHPMD.php(54): Qafoo\Analyzer\Shell->exec('/opt/QualityAna...', Array, Array)
#1 /opt/QualityAnalyzer/src/php/Qafoo/Analyzer/Command/Analyze.php(136): Qafoo\Analyzer\Handler\PHPMD->handle(Object(Qafoo\Analyzer\Project), NULL)
#2 /opt/QualityAnalyzer/vendor/symfony/console/Command/Command.php(259): Qafoo\Analyzer\Command\Analyze->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /opt/QualityAnalyzer/vendor/symfony/console/Application.php(849): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /opt/QualityAnalyzer/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Qafoo\Analyzer\Command\Analyze), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /opt/QualityAnalyzer/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /opt/QualityAnalyzer/bin/analyze(15): Symfony\Component\Console\Application->run()
#7 {main}
 * Running checkstyle
```

**Comment by Mte90** [comment]
As I can see the folder in tmp the folder not exist but the script is executed with a rule where I create usually folder in /tmp

**Comment by Mte90** [comment]
Ok in Shell.php file I changed the 85 line: `return mkdir(sys_get_temp_dir(). '/' . $prefix . '-' . rand());` and now create the folder.

**Comment by Mte90** [comment]
Uhm as I can see now I get: `PHP Warning:  ZipArchive::close(): Read error: Is a directory in /opt/QualityAnalyzer/src/php/Qafoo/Analyzer/Handler/Source.php on line 46`

**Comment by Mte90** [comment]
That errors seem by Php 7 http://php.net/manual/en/ziparchive.close.php#119960

**Comment by metamaker** [comment]
Still having the same problem.
