### ISSUE TITLE
Invalid arguments when invoking zip

### ISSUE THREAD

**Issue by lstrojny** [Qafoo/QualityAnalyzer#6]
```
exception 'Exception' with message 'Program exited with non zero exit code 16:
zip error: Invalid command arguments (option 'x' (exclude files matching patterns) requires a value)' in /Users/lstrojny/Projects/InterNations/QualityAnalyzer/src/php/Qafoo/Analyzer/Shell.php:41
Stack trace:
#0 /Users/lstrojny/Projects/InterNations/QualityAnalyzer/src/php/Qafoo/Analyzer/Handler/Source.php(62): Qafoo\Analyzer\Shell->exec('zip', Array)
#1 /Users/lstrojny/Projects/InterNations/QualityAnalyzer/src/php/Qafoo/Analyzer/Command/Analyze.php(104): Qafoo\Analyzer\Handler\Source->handle('/Users/lstrojny...', Array, NULL, NULL)
#2 /Users/lstrojny/Projects/InterNations/QualityAnalyzer/vendor/symfony/console/Command/Command.php(259): Qafoo\Analyzer\Command\Analyze->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/lstrojny/Projects/InterNations/QualityAnalyzer/vendor/symfony/console/Application.php(878): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/lstrojny/Projects/InterNations/QualityAnalyzer/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Qafoo\Analyzer\Command\Analyze), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/lstrojny/Projects/InterNations/QualityAnalyzer/vendor/symfony/console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/lstrojny/Projects/InterNations/QualityAnalyzer/bin/analyze(9): Symfony\Component\Console\Application->run()
```

**Comment by lstrojny** [comment]
Not OS X related, I get the same error on a Debian VM

**Comment by lstrojny** [comment]
It happens if the excludes end with a slash. So e.g. `--exclude=vendor/` triggers that behavior.

**Comment by kore** [comment]
Funnily it didn't work here without adding a trailing `/` … I will investigate zipping options without using the CLI. Should make it more reliable across platforms.

**Comment by kore** [comment]
Done. Please reopen if your issues are not fixed. Thanks for reporting this issue.
