### ISSUE TITLE
'zip' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by edsonmedina** [Qafoo/QualityAnalyzer#8]
Getting this on windows:

```
Analyze source code in C:\xxx\xxx\xxx
 * Running source
'zip' is not recognized as an internal or external command,
operable program or batch file.
exception 'Exception' with message 'Program exited with non zero exit code 1: ' in C:\Users\emedina\QualityAnalyzer\src\php\Qafoo\Analyzer\Shell.php:41
Stack trace:
#0 C:\Users\emedina\QualityAnalyzer\src\php\Qafoo\Analyzer\Handler\Source.php(62): Qafoo\Analyzer\Shell->exec('zip', Array)
#1 C:\Users\emedina\QualityAnalyzer\src\php\Qafoo\Analyzer\Command\Analyze.php(104): Qafoo\Analyzer\Handler\Source->handle('C:\\inetpub\\wwwr...', Array, NULL, NULL)
#2 C:\Users\emedina\QualityAnalyzer\vendor\symfony\console\Command\Command.php(259): Qafoo\Analyzer\Command\Analyze->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\Users\emedina\QualityAnalyzer\vendor\symfony\console\Application.php(878): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\Users\emedina\QualityAnalyzer\vendor\symfony\console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Qafoo\Analyzer\Command\Analyze), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\Users\emedina\QualityAnalyzer\vendor\symfony\console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\Users\emedina\QualityAnalyzer\bin\analyze(9): Symfony\Component\Console\Application->run()
#7 {main}
 * Running coverage
 * Running pdepend

**Comment by knezmilos13** [comment]
Same thing here, Windows 7 with Wamp 2.5 and PHP 5.5.12

```
Analyze source code in C:\wamp\www\wow-backend
 * Running source
'zip' is not recognized as an internal or external command,
operable program or batch file.
exception 'Exception' with message 'Program exited with non zero exit code 1: '
in C:\wamp\www\QualityAnalyzer\src\php\Qafoo\Analyzer\Shell.php:41
Stack trace:
#0 C:\wamp\www\QualityAnalyzer\src\php\Qafoo\Analyzer\Handler\Source.php(62): Qafoo\AnalyzerShell->exec('zip', Array)
#1 C:\wamp\www\QualityAnalyzer\src\php\Qafoo\Analyzer\Command\Analyze.php(104):Qafoo\Analyzer\Handler\Source->handle('C:\\wamp\\www\\wow...', Array, NULL, NULL)
#2 C:\wamp\www\QualityAnalyzer\vendor\symfony\console\Command\Command.php(259):Qafoo\Analyzer\Command\Analyze->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\wamp\www\QualityAnalyzer\vendor\symfony\console\Application.php(878): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\wamp\www\QualityAnalyzer\vendor\symfony\console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Qafoo\Analyzer\Command\Analyze), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\wamp\www\QualityAnalyzer\vendor\symfony\console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\wamp\www\QualityAnalyzer\bin\analyze(9): Symfony\Component\Console\Application->run()
#7 {main}
 * Running coverage
 * Running pdepend
````

**Comment by tomzx** [comment]
`zip` is expected to be available on the users' path, which may not be the case for windows users.

Furthermore, it would be a good idea to indicate such dependencies in the README.

**Comment by knezmilos13** [comment]
^Interesting that the documentation states "The only requirement is a current version of PHP" which is clearly not true.

**Comment by fruitl00p** [comment]
Couldn't it be included in the composer file as a platform dependency?

**Comment by kore** [comment]
Switched to the PHP zip extension (http://docs.php.net/zip) and added it as a requirement to the `composer.json`. Should fix this.

Feel free to reopen if there are still issues with this. Thanks for reporting your issues.
